openapi: 3.1.0
x-stoplight:
  id: vtlm0zmf003iu
info:
  title: Catalyst 1.0
  description: |-
    Revised API expressing all capabilities of the Catalyst 1.0 Backend.

    TODO:
    * Implement Permissionless Auth.
    * Implement Replacement Functionality for GVC.
    * Implement drep registration on main-chain, distinct from voter registration.
    * Implement Voting API abstracting the Jormungandr API from public exposure.
    * Implement Audit API's (Retrieve voting blockchain records,  registration/voting power audit and private tally audit.
    * Implement API's needed to support posting Ideas/Proposals etc.
  version: 1.0.0
  contact:
    name: Steven Johnson
    email: steven.johnson@iohk.io
    url: 'https://github.com/input-output-hk/catalyst-core'
  termsOfService: 'https://github.com/input-output-hk/catalyst-core/blob/main/README.md'
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  summary: Catalyst 1.0 API
tags:
  - name: event
    description: Information on voting events.
  - name: objective
    description: Information about the objectives in which all the people in a defined group decide on an important question.
  - name: proposal
    description: Information on the proposals to be considered in context with their objective.
  - name: registration
    description: 'Information relating to Voter Registration, Delegations and Calculated Voting Power.'
  - name: ballot
    description: Ballot and Voting operations.
  - name: search
    description: Search operations.
servers:
  - url: 'http://localhost:{port}'
    description: Local Testing Only
    variables:
      port:
        default: '8123'
  - url: 'https://dev.xxxxxxxxxxxxxx.io'
    description: Unstable Development Test Environment
  - url: 'https://qa.xxxxxxxxxxxxxx.io'
    description: QA Testing Environment
  - url: 'https://preprod.xxxxxxxxxxxxxx.io'
    description: Preprod Stable Contiunous Testing Environment
  - url: 'https://prod.xxxxxxxxxxxxxx.io'
    description: Production Environment
paths:
  /api/v1/events:
    get:
      operationId: getEvents
      summary: Get Voting Events.
      tags:
        - event
      description: |
        Get list of all currently known past, present and future Voting Events.
      responses:
        '200':
          description: List of all known Voting Events.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventSummary'
        '500':
          $ref: '#/components/responses/500'
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
  '/api/v1/event/{id}':
    parameters:
      - $ref: '#/components/parameters/event_id'
    get:
      operationId: getEvent
      summary: Get Individual Voting Event Details
      tags:
        - event
      description: |
        Retrieves all information about the requested Voting Event.
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          $ref: '#/components/responses/404-Event'
        '500':
          $ref: '#/components/responses/500'
  '/api/v1/event/{id}/objectives':
    parameters:
      - $ref: '#/components/parameters/event_id'
    get:
      operationId: getObjectives
      summary: Get objectives to be decided for a Voting Event.
      tags:
        - objective
      description: |-
        Get all current objectives to be decided for the voting event.
        An Objective here is defined as:\
        *"A vote in which all the people in a group decide on an important issue."*\
        Examples of objectives are:
        * Catalsyt Funding Challenges
        * General Voting Events
        * Any other Decision to be determined by the Communities Collective will.
        * Non binding community collective opinion measurement.
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ObjectiveSummary'
                    x-stoplight:
                      id: bsz8o5nnhtu9e
                  - $ref: '#/components/schemas/ObjectiveDetails'
                    x-stoplight:
                      id: mdciat4uo1xu8
        '404':
          description: The requested challenge was not found
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/voter_groups_filter'
  '/api/v1/event/{id}/{obj_id}/proposals':
    parameters:
      - $ref: '#/components/parameters/event_id'
      - $ref: '#/components/parameters/obj_id'
    get:
      operationId: getAllProposals
      summary: Get summary all available proposals
      tags:
        - proposal
      description: |
        Lists all available proposals.
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ProposalWithChallengeInfo'
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/voter_groups_filter'
  '/api/v1/event/{id}/{obj_id}/{prop_id}/proposal':
    parameters:
      - $ref: '#/components/parameters/event_id'
      - $ref: '#/components/parameters/obj_id'
      - $ref: '#/components/parameters/prop_id'
    get:
      operationId: getProposal
      summary: Get Individual Proposal data
      tags:
        - proposal
      description: |
        Retrieves information on the identified proposal if it belongs to the provided group.
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProposalWithChallengeInfo'
        '404':
          description: The requested proposal was not found
  '/api/v1/event/{id}/{obj_id}/{prop_id}/reviews':
    parameters:
      - $ref: '#/components/parameters/event_id'
      - $ref: '#/components/parameters/obj_id'
      - $ref: '#/components/parameters/prop_id'
    get:
      operationId: getProposalReviews
      summary: Get reviews related to a proposal
      tags:
        - proposal
      description: |
        Retrieves advisor reviews information for the provided proposal id.
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvisorReviews'
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
  /api/v1/search:
    post:
      summary: Search various resources with various constraints
      operationId: search
      tags:
        - search
      description: Search various resources especially challenges and proposals with various constraints like contains some string etc.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchQuery'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/ObjectiveSummary'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ProposalWithChallengeInfo'
        '400':
          description: Invalid combination of table/column (e.g. using funds column on challenges table)
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/totals'
    parameters: []
  '/api/v1/registration/voter/{vkey}':
    parameters:
      - name: vkey
        in: path
        required: true
        schema:
          type: string
        description: A Voting Key.
    get:
      operationId: getVoterInfo
      summary: Get voter's info by voting key
      tags:
        - registration
      description: |
        Get voter's registration and voting power by their voting key.\
        If the `eid` query parameter is omitted, then the latest voting power is retrieved.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VotersInfo'
        '400':
          description: There is an error with the request.
        '404':
          description: Voting Key not found for requested event.
      parameters:
        - $ref: '#/components/parameters/event_id_filter'
  '/api/v1/registration/delegations/{sp_key}':
    parameters:
      - $ref: '#/components/parameters/stake_public_key'
    get:
      operationId: getDelegatorInfo
      summary: Get voters info by stake public key
      tags:
        - registration
      description: |
        Get voters delegation info by stake public key.\
        If the `eid` query parameter is missing, then the "Latest" registration for the Stake Public Key is returned.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelegatorInfo'
        '400':
          description: An error occured
        '404':
          description: Stake Address for the event was not found in the snapshot.
      parameters:
        - $ref: '#/components/parameters/event_id_filter'
  /api/v1/ballot/check:
    post:
      summary: Check Ballot Validity
      operationId: post-api-v1-ballot-check
      tags:
        - ballot
      responses:
        '200':
          description: OK
      description: |-
        Check if a Ballot is correctly formatted and signed.
        This endpoint is to check all possible aspects of an individual ballot and return a report details what is correct, and what is incorrect.
        The actual format of the report is TBD on implementation.
        It is to handle both Private and Public Ballots.

        If Event ID is provided, the ballot should also be checked against current knowledge of the Events Objectives and Proposals to check the contents of the ballot are correct.  Otherwise, they are not considered and ONLY the raw format is checked.

        It must also check the Ballot is signed properly with the voters private voting key.

        If an event is supplied, it should also check if the Voting Key is registered and eligible to vote on the event.
        If no event is supplied, it should check if the "latest" snapshot contains a registration for this voting key.  If it does not, this is not an Error, but a warning status should be returned.
  '/api/v1/ballot/cast/{id}':
    parameters:
      - $ref: '#/components/parameters/event_id'
    get:
      summary: Your GET endpoint
      tags:
        - ballot
      responses: {}
      operationId: get-api-v1-ballot-cast-id
      description: Cast a Ballot on the requested Voting Event.
  '/api/v1/ballot/proof/{vkey}/{id}':
    post:
      summary: Get Ballot Proof
      operationId: getBallotProofs
      description: Get list of details and ballot proofs for every currently cast ballot on a particular voting event for a particular voting key.
      requestBody:
        description: List of votes by voteplan id and caster (wallet)
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VotesByVoteCasterAndVoteplanId'
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoteInfo'
      x-internal: true
      deprecated: true
      tags:
        - ballot
    parameters:
      - $ref: '#/components/parameters/voting_key'
      - $ref: '#/components/parameters/event_id'
components:
  schemas:
    DateTime:
      title: DateTime
      x-stoplight:
        id: gyp8fm05q2wcm
      type: string
      format: date-time
      example: '2023-08-24T14:15:22Z'
      pattern: '^(\d+)-(0[1-9]|1[012])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d|60)(\.\d+)?([Zz])$'
      description: RFC3339 DateTime String UTC.
    EventId:
      title: EventId
      x-stoplight:
        id: mql4l8ntzqfjc
      type: integer
      description: The Numeric ID of a Voting Event
      example: 11
      format: int32
      minimum: 0
    EventName:
      title: EventName
      x-stoplight:
        id: 0bexxtej703en
      type: string
      description: The Name of a Voting Event
      x-examples:
        Example 1: Fund-12
        Example 2: SVE-1
      pattern: '^[A-Z][\w-]+$'
      minLength: 2
      example: Fund-12
    EventSummary:
      title: EventSummary
      x-stoplight:
        id: 1ueealg841s72
      type: object
      x-examples: {}
      properties:
        id:
          $ref: '#/components/schemas/EventId'
        name:
          $ref: '#/components/schemas/EventName'
        starts:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when the Voting Event commences.
        ends:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when the Voting Event is expected to finish.
        finalized:
          type: boolean
          description: True if the event is finished and no changes can be made to it.<br>Does not Including payment of rewards or funding of projects.
        reg_checked:
          $ref: '#/components/schemas/DateTime'
          description: 'Last time registrations and Voting power were checed.If not present, no registration or voting power records exist for this event.'
      required:
        - id
        - name
      description: A Summary of an individual Voting Event
    VotingPowerSettings:
      title: Voting Power Settings
      type: object
      description: The Settings Used to configure the voting power calculation.
      properties:
        alg:
          type: string
          example: threshold_staked_ADA
          description: |-
            The Voting Power Algorithm.

            * `threshold_staked_ADA` = "Linear Voting Power in Staked ADA, With a minimum limit and maximum relative threshold.
          enum:
            - threshold_staked_ADA
        min_ada:
          type: integer
          format: int64
          description: |-
            Minimum staked funds required for a valid voter registration.
            This amount is in Whole ADA. If not present, there is no minimum.\
            Valid for `alg`:
            * `threshold_staked_ADA`
          example: 500
        max_pct:
          type: number
          format: float
          example: 1
          description: |-
            Maximum Percentage of total registered voting power allowed for voting power.
            For example `1.23` = `1.23%` of total registered staked ADA as maximum voting power.
            If not present, there is no maximum percentage.\
            Valid for `alg`:
            * `threshold_staked_ADA`
      required:
        - alg
      x-stoplight:
        id: q0j4rnd7me3d5
    EventGoal:
      title: Event Goal
      type: object
      description: An Individual Event Goal
      properties:
        idx:
          type: integer
          description: The Realtive order of this Goal. 0 being highest.
          example: 2
          format: int32
        name:
          type: string
          description: The name/short description of the goal.
          maxLength: 40
      required:
        - idx
        - name
      x-stoplight:
        id: 1cowh1sigko19
    EventGoals:
      title: Event Goals
      type: array
      description: The ordered goals of the voting event.
      uniqueItems: true
      minItems: 1
      items:
        $ref: '#/components/schemas/EventGoal'
      x-stoplight:
        id: rmjom0j9d81e6
    EventRegistration:
      title: Event Registration
      type: object
      description: Details about Voting Event Registration
      properties:
        purpose:
          type: integer
          description: The Registration Purpose.
          example: 2
          format: int32
          minimum: 0
          default: 0
        deadline:
          $ref: '#/components/schemas/DateTime'
          description: |-
            The deadline for Registration/Voting Power to be fixed.
            Changes to Registrations or Voting power after this time are not considered.
        taken:
          $ref: '#/components/schemas/DateTime'
          description: |-
            The time after which Final Registration/Voting Power will be calculated.
            This is usually after the deadline, to allow for potential instability in the head of the blockchain to stabilize.
      required:
        - deadline
        - taken
      examples:
        - deadline: '2023-08-24T14:15:22Z'
          taken: '2023-08-24T14:15:22Z'
        - purpose: 2
          deadline: '2023-08-24T14:15:22Z'
          taken: '2023-08-24T14:15:22Z'
      x-stoplight:
        id: 7l9i6nj2pd1hg
    EventSchedule:
      title: EventSchedule
      type: object
      description: |-
        The chronological sequence of stages of the voting event.\
        Stages run chronolgically and only 1 stage can run at a time.\
        Each new stage terminates the previous stage.\
        Any ommitted entries are assumed to not exist as a stage in this event.
      properties:
        insight_sharing:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Insight Sharing Starts.
        proposal_submission:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Proposals can be submitted to the Voting Event.
        refine_proposals:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Proposal refinement begins.
        finalize_proposals:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Proposal Finalization starts.
        proposal_assessment:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Proposal Assessment starts.
        assessment_qa_start:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Assessment QA starts.
        voting:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Voting commences.
        tallying:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Voting ends and tallying commences.
        tallying_end:
          $ref: '#/components/schemas/DateTime'
          description: Date-Time when Tallying Ends.
      required:
        - voting
        - tallying
        - tallying_end
      x-stoplight:
        id: c1q1b5jtfd4ue
    ObjectiveId:
      title: ObjectiveId
      x-stoplight:
        id: x36yug5b7c3r8
      type: integer
      description: The Numeric ID of an Objecgtive to be decided in a Voting Event
      example: 11
      format: int32
      minimum: 0
    EventDetails:
      title: EventDetails
      x-stoplight:
        id: lnivx8gtyvbcn
      type: object
      description: Detaild information for an individual voting event.
      properties:
        voting_power:
          $ref: '#/components/schemas/VotingPowerSettings'
          description: How Voting Power is Calculated and its parameters.
        registration:
          $ref: '#/components/schemas/EventRegistration'
          description: Registration deadlines and when its finalized.  Plus any other parameters.
        goals:
          $ref: '#/components/schemas/EventGoals'
          description: |-
            Description of the voting events goals.
            If this field is not present, there are no listed goals for the event.
        schedule:
          $ref: '#/components/schemas/EventSchedule'
          description: The schedule of the voting Event
        groups:
          type: array
          description: The valid voter groups for this voting event.
          items:
            $ref: '#/components/schemas/VoterGroup'
    Event:
      allOf:
        - $ref: '#/components/schemas/EventSummary'
        - $ref: '#/components/schemas/EventDetails'
      description: Complete Details about an individual Voting Event
      x-stoplight:
        id: 4cx75nmf74wdd
    ObjectiveTypes:
      type: string
      enum:
        - catalyst-simple
        - catalyst-native
        - catalyst-community-choice
        - sve-decision
      description: Objective Type defines the rules of the objective.
      x-stoplight:
        id: 098z8z1pwtkj2
    ObjectiveType:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ObjectiveTypes'
        description:
          type: string
          description: An explanaiton of the rules of this Objective Type.
      x-stoplight:
        id: x7nhy2qu3xwrv
    RewardCurrency:
      type: string
      enum:
        - USD_ADA
        - ADA
        - CLAP
        - COTI
      description: Currency of the Reward.
      x-stoplight:
        id: 9ng0ptdxjm60i
    RewardDefintion:
      type: object
      x-stoplight:
        id: uncc6j7uf38ge
      properties:
        currency:
          $ref: '#/components/schemas/RewardCurrency'
        value:
          type: integer
          format: int64
          description: The total value of the reward
      required:
        - currency
        - value
    ObjectiveChoices:
      type: array
      description: |-
        Ordered list of choices available for all proposals in this Objective.
        The offset into the array is the index of the choice.
        For example, the first element is Choice 0, second is Choice 1 and so on.
      x-stoplight:
        id: ym16khzb1abc4
      examples:
        - - Abstain
          - 'No'
          - 'Yes'
      minItems: 1
      maxItems: 16
      uniqueItems: true
      items:
        type: string
        minLength: 1
    BallotType:
      type: string
      description: |-
        The kind of ballot to be cast on this Objective.
        * `public` - All Ballots are public when cast.
        * `private` - All Ballots are private.
        * `cast-private` - All Ballots are cast privately but become public after the tally.
      x-stoplight:
        id: 1sv4pgkgu83u6
      enum:
        - public
        - private
        - temp-private
      examples:
        - private
        - public
        - cast-private
      minItems: 1
      maxItems: 16
      uniqueItems: true
      items:
        type: string
        minLength: 1
    GroupBallotType:
      title: Group Ballot Type
      type: array
      minItems: 1
      uniqueItems: true
      description: |-
        List of Voter Groups and the kind of ballot they must cast.
        Each voter group that can vote on the objective:
        * MUST be listed.
        * MUST be listed only once.
      items:
        type: object
        properties:
          group:
            $ref: '#/components/schemas/VoterGroupId'
            description: The name of the group (Must be unique in the array).
          ballot:
            $ref: '#/components/schemas/BallotType'
            description: The type of ballot this group must cast.
      x-stoplight:
        id: qaz93o6qdkr5c
    ObjectiveSupplementalData:
      title: Objective Supplemental Data
      x-stoplight:
        id: hrsvblk9q7ju1
      type: object
      description: |-
        Extra Data which can be used to enrich the information shared about the Objective.
        All Information here is optional.
        If there is no supplemental information for the Objective this field is omitted.
      properties:
        sponser:
          type: string
          description: Who is sponsoring this Objective.
        video:
          type: string
          format: uri
          description: Link to a video about this Objective
    ObjectiveSummary:
      title: Objective Summary
      x-stoplight:
        id: rjgmuk6r5pdf5
      description: Summary off an Individual Objective
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ObjectiveId'
          description: The ID of this objective for the Voting Event
        type:
          $ref: '#/components/schemas/ObjectiveType'
          description: The "Type" of Objective
        title:
          type: string
          description: The title for this Objective.
      required:
        - id
        - type
        - title
    ObjectiveDetails:
      title: Objective Details
      x-stoplight:
        id: 015aa65365c13
      description: Individual Objective Details
      type: object
      properties:
        description:
          type: string
          description: |-
            Long form explanation of this particular objective.\
            *May contain HTML Markup.*\
            *May contain Links to external content or assets.*
        reward:
          $ref: '#/components/schemas/RewardDefintion'
          description: |-
            The Total Reward being offered for this Objective.
            Distribuition of the Reward is determined under the rules of this Objective.
            If this field is not present there is no reward being offered for the Objective.
        choices:
          $ref: '#/components/schemas/ObjectiveChoices'
          description: Ballot Choices present for all proposals in this Objective.
        ballot:
          $ref: '#/components/schemas/GroupBallotType'
          description: The types of Ballot each group may cast.
        url:
          type: string
          description: External URL that better describes the Objective.
          format: uri
        supplemental:
          $ref: '#/components/schemas/ObjectiveSupplementalData'
    VotePlan:
      type: object
      description: The votplan to use for this group.
      properties:
        group:
          $ref: '#/components/schemas/VoterGroupId'
          description: The name of the group (Must be unique in the array).
        chain_voteplan_id:
          type: string
          format: hash
          description: Blockchain ID of the vote plan transaction.
      x-stoplight:
        id: owvld2uvjjnty
    GroupVotePlans:
      type: array
      description: |-
        List of groups and the voteplans they use when voting on this proposal.
        Each valid group for this Objective:
          * Must be listed.
          * Must not be repeated.
      items:
        $ref: '#/components/schemas/VotePlan'
    ProposalSummary:
      type: object
      description: Summary of a Proposal for an Objective
      properties:
        internal_id:
          type: integer
          format: int32
          description: The API identifier for this proposal.
        proposal_id:
          type: string
          description: Unique identifier for this proposal.
        proposal_category:
          type: object
          properties:
            category_id:
              type: string
            category_name:
              type: string
            category_description:
              type: string
        proposal_title:
          type: string
          description: Short title of the proposal.
        proposal_summary:
          type: string
          description: Brief description of the proposal.
        proposal_public_key:
          type: string
          format: binary
        proposal_funds:
          type: integer
          format: int64
          description: The amount of funds requested by this proposal.
        proposal_url:
          type: string
          description: URL to a web page with details on this proposal.
        proposal_files:
          type: string
        proposal_extra_fields:
          type: object
          description: Map of proposal's extra fields.
        proposer:
          type: object
          properties:
            proposer_name:
              type: string
              description: Name of the author of the proposal.
            proposer_email:
              type: string
              description: Email address of the author of the proposal.
            proposer_url:
              type: string
              description: URL to a web resource with details about the author of the proposal.
        chain_proposal_id:
          type: string
          description: Identifier of the proposal on the blockchain.
        chain_vote_options:
          description: Map of named vote options to choice indices.
          type: object
        chain_vote_start_time:
          type: string
          format: date-time
          description: Date and time for the start of voting on this proposal's vote plan.
        chain_vote_end_time:
          type: string
          format: date-time
          description: Date and time for the start of voting on this proposal's vote plan.
        chain_committee_end_time:
          type: string
          format: date-time
          description: Date and time for the end of tallying on this proposal's vote plan.
        chain_voteplan_payload:
          type: string
          description: |
            Whether the voting is done using the public or the privacy-preserving protocol.
        chain_voteplan_id:
          type: string
          description: Identifier of the vote plan a proposal belongs to.
        chain_proposal_index:
          type: integer
          format: int64
          description: Index of a proposal in the vote plan.
      x-stoplight:
        id: 17qab7opa4jhd
    Proposal:
      properties:
        internal_id:
          type: integer
          format: int32
          description: The API identifier for this proposal.
        proposal_id:
          type: string
          description: Unique identifier for this proposal.
        proposal_category:
          type: object
          properties:
            category_id:
              type: string
            category_name:
              type: string
            category_description:
              type: string
        proposal_title:
          type: string
          description: Short title of the proposal.
        proposal_summary:
          type: string
          description: Brief description of the proposal.
        proposal_public_key:
          type: string
          format: binary
        proposal_funds:
          type: integer
          format: int64
          description: The amount of funds requested by this proposal.
        proposal_url:
          type: string
          description: URL to a web page with details on this proposal.
        proposal_files:
          type: string
        proposal_extra_fields:
          type: object
          description: Map of proposal's extra fields.
        proposer:
          type: object
          properties:
            proposer_name:
              type: string
              description: Name of the author of the proposal.
            proposer_email:
              type: string
              description: Email address of the author of the proposal.
            proposer_url:
              type: string
              description: URL to a web resource with details about the author of the proposal.
        chain_proposal_id:
          type: string
          description: Identifier of the proposal on the blockchain.
        chain_vote_options:
          description: Map of named vote options to choice indices.
          type: object
        chain_vote_start_time:
          type: string
          format: date-time
          description: Date and time for the start of voting on this proposal's vote plan.
        chain_vote_end_time:
          type: string
          format: date-time
          description: Date and time for the start of voting on this proposal's vote plan.
        chain_committee_end_time:
          type: string
          format: date-time
          description: Date and time for the end of tallying on this proposal's vote plan.
        chain_voteplan_payload:
          type: string
          description: |
            Whether the voting is done using the public or the privacy-preserving protocol.
        chain_voteplan_id:
          type: string
          description: Identifier of the vote plan a proposal belongs to.
        chain_proposal_index:
          type: integer
          format: int64
          description: Index of a proposal in the vote plan.
      x-stoplight:
        id: 77fsb753m3ssh
    ChallengeType:
      type: string
      enum:
        - simple
        - community-choice
      x-stoplight:
        id: d19h4jdajfv0k
    ProposalWithChallengeInfo:
      discriminator:
        propertyName: challenge_type
        mapping:
          simple: '#/components/schemas/SimpleProposal'
          community-choice: '#/components/schemas/CommunityChoiceProposal'
      allOf:
        - $ref: '#/components/schemas/Proposal'
        - type: object
          properties:
            fund_id:
              type: integer
              format: int32
            challenge_id:
              type: integer
              format: int32
            reviews_count:
              type: integer
              format: int32
              description: Total amount of individual reviews per assessor
            challenge_type:
              $ref: '#/components/schemas/ChallengeType'
      x-stoplight:
        id: 0o6uwmcpjnf95
    SimpleProposal:
      allOf:
        - $ref: '#/components/schemas/ProposalWithChallengeInfo'
        - type: object
          properties:
            proposal_solution:
              type: string
      example:
        internal_id: 22
        proposal_id: 4af0e6b3452cd4ee822b2ec1859fd57b5512f85c14875f408081aa9b796dfc6e
        proposal_title: Authentication for DeepFake Defense
        proposal_summary: Deepfake videos are dangerous.
        proposal_solution: We will create a cryptographic proof on Cardano that verifies videos are real by connecting their blockchain ID.
        proposal_public_key: Fvd8zI3DH85qnaChQE6Aymt1diMJP32LB0AdpheZh/Q=
        proposal_funds: 12000
        proposal_url: 'http://ideascale.com/t/UM5UZBd2t'
        proposal_files_url: ''
        proposal_impact_score: 0
        proposer:
          proposer_name: Community Member
          proposer_email: example@vit.iohk.io
          proposer_url: ''
          proposer_relevant_experience: 'Cryptography student, website development, blockchain technologist.'
        chain_proposal_id: 4af0e6b3452cd4ee822b2ec1859fd57b5512f85c14875f408081aa9b796dfc6e
        chain_vote_options:
          blank: 0
          'yes': 1
          'no': 2
        chain_vote_start_time: '2021-02-10T14:40:27+00:00'
        chain_vote_end_time: '2021-02-11T10:10:27+00:00'
        chain_committee_end_time: '2021-02-11T11:40:27+00:00'
        chain_voteplan_payload: public
        chain_vote_encryption_key: ''
        fund_id: 20
        challenge_id: 2
        challenge_type: simple
      x-stoplight:
        id: hi49phkn54hvh
    CommunityChoiceProposal:
      allOf:
        - $ref: '#/components/schemas/ProposalWithChallengeInfo'
        - type: object
          properties:
            proposal_brief:
              type: string
            proposal_importance:
              type: string
            proposal_goal:
              type: string
            proposal_metrics:
              type: string
      example:
        internal_id: 31
        proposal_id: 494d8d685e3b195eb5610494f1721db7747df0517cb1b6a705bb3cebfef3c998
        proposal_title: A for ADA Cryptoalphabet 4 children
        proposal_summary: |-
          How to increase general awareness about Cardano and cryptocurrencies?
          How to make fun community-building incentives?
        proposal_brief: A for ADA
        proposal_importance: We need to get them while they're young.
        proposal_goal: Nebulous.
        proposal_metrics: \- Number of people engaged into the creation of Cryptoalphabet
        proposal_public_key: zqUCWwguCt6+NHYjkpvasvccuA7l2SuabE+1C0bzf3Y=
        proposal_funds: 4800
        proposal_url: 'http://ideascale.com/t/UM5UZBd1p'
        proposal_files_url: ''
        proposal_impact_score: 133
        proposer:
          proposer_name: Community Member
          proposer_email: example@vit.iohk.io
          proposer_url: ''
          proposer_relevant_experience: ''
        chain_proposal_id: 494d8d685e3b195eb5610494f1721db7747df0517cb1b6a705bb3cebfef3c998
        chain_proposal_index: 9
        chain_vote_options:
          'no': 2
          'yes': 1
          blank: 0
        chain_voteplan_id: b1eeb620baf1445672f6c9422481aff0f6babaf775760d187a7703027e098166
        chain_vote_start_time: '2021-02-10T14:40:27+00:00'
        chain_vote_end_time: '2021-02-11T10:10:27+00:00'
        chain_committee_end_time: '2021-02-11T11:40:27+00:00'
        chain_voteplan_payload: public
        chain_vote_encryption_key: ''
        fund_id: 20
        challenge_id: 1
        challenge_type: community-choice
      x-stoplight:
        id: zcugwyfdn78qf
    AdvisorReview:
      properties:
        id:
          type: integer
          format: i32
        proposal_id:
          type: integer
          format: i32
        assessor:
          type: string
        impact_alignment_rating_given:
          $ref: '#/components/schemas/Rating'
        impact_alignment_note:
          type: string
        feasibility_rating_given:
          $ref: '#/components/schemas/Rating'
        feasibility_note:
          type: string
        auditability_rating_given:
          $ref: '#/components/schemas/Rating'
        auditability_note:
          type: string
        ranking:
          description: Measure of quality of this review according to veteran community advisors
          type: string
          enum:
            - Excellent
            - Good
            - FilteredOut
            - NA
      x-stoplight:
        id: awwbn3ijzu3f7
    Rating:
      type: integer
      format: i32
      minimum: 0
      maximum: 500
      description: 'Rating in range [0, 500] (0 stars to 5 stars)'
      x-stoplight:
        id: 2094oy7m3jnrb
    AdvisorReviews:
      type: array
      items:
        $ref: '#/components/schemas/AdvisorReview'
      example:
        - id: 1
          proposal_id: 1234
          rating_given: 0
          assessor: za_assessor_432
          note: foo bar
          tag: Alignment
      x-stoplight:
        id: qfzi1fjnjnxup
    ProposalsByVoteplanIdAndIndexQuery:
      type: array
      items:
        $ref: '#/components/schemas/ProposalVoteplanIdAndIndex'
      x-stoplight:
        id: lrg71jd76p1ce
    ProposalVoteplanIdAndIndex:
      properties:
        voteplan_id:
          type: string
        indexes:
          type: array
          items:
            type: integer
            format: i64
      x-stoplight:
        id: vy229ii49fc49
    VotesByVoteCasterAndVoteplanId:
      properties:
        vote_plan_id:
          type: string
          format: hash
          description: Blockchain ID of the vote plan transaction.
        caster:
          type: string
          format: hash
          description: public key of caster wallet
      x-stoplight:
        id: ufax8ri60bljs
    VoteInfo:
      properties:
        fragment_id:
          type: string
          format: hash
          description: Blockchain ID of the vote plan transaction
        caster:
          type: string
          format: hash
          description: public key of caster wallet
        proposal:
          type: integer
          format: int32
          description: proposal index within voteplan
        voteplan_id:
          type: string
          format: hash
          description: Blockchain ID of the vote plan transaction
        time:
          type: number
          format: f32
          description: block date in format epoch.slot_no
        choice:
          type: string
          format: byte
          description: vote choice (only visible for public voting)
        raw_fragment:
          type: string
          format: hash
          description: raw bytes of transaction
      x-stoplight:
        id: 4j0mbaifceat2
    SearchQuery:
      properties:
        table:
          $ref: '#/components/schemas/SearchConstraint'
        filter:
          type: array
          items:
            $ref: '#/components/schemas/SearchConstraint'
        order-by:
          type: array
          items:
            $ref: '#/components/schemas/SearchOrderBy'
        limit:
          type: integer
          format: i32
          description: Sets the limit clause of the search query.
        offset:
          type: integer
          format: i32
          description: Sets the offset clause of the search query.
      required:
        - table
      x-stoplight:
        id: 71ygwitz1u1yo
    SearchConstraint:
      properties:
        column:
          $ref: '#/components/schemas/SearchColumn'
        search:
          type: string
          description: Text which must be present in the given column (case insensitive)
      required:
        - column
        - search
      x-stoplight:
        id: c0gos4aazkpsk
    SearchOrderBy:
      properties:
        column:
          $ref: '#/components/schemas/SearchColumn'
        descending:
          type: boolean
          default: false
      required:
        - column
      x-stoplight:
        id: yj4axohjjidlc
    SearchTable:
      type: string
      enum:
        - events
        - objectives
        - proposals
      x-stoplight:
        id: dfnjjpi34lxjp
    SearchColumn:
      type: string
      enum:
        - title
        - type
        - desc
        - author
        - funds
      x-stoplight:
        id: 0rd8jpsoczvvt
    VoterGroupId:
      title: VoterGroupId
      x-stoplight:
        id: 538gfz6zp2u5h
      type: string
      default: direct
      example: rep
      x-examples:
        Direct Voter: direct
        Registered Delegated Representative: rep
      enum:
        - direct
        - rep
      description: Voters Group ID.</br>`direct` = Direct voter.</br>`rep` = Delegated Representative.
    VoterGroup:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/VoterGroupId'
        voting_token:
          type: string
          pattern: '[0-9a-f]{56}(\.[0-9a-f]{1,64})?'
          description: |
            The identifier of voting power token used withing this group.
            All vote plans within a group are guaranteed to use the same token.
      x-stoplight:
        id: ckmvgc5nnbhsv
    VotersInfo:
      type: object
      description: The voting power for the requested voting key.
      properties:
        voter_info:
          type: array
          items:
            $ref: '#/components/schemas/VoterInfo'
        last_updated:
          type: string
          format: date-time
          description: Date and time for the latest update to this snapshot information.
        as_at:
          type: string
          format: date-time
          description: Date and time the latest snapshot represents.
        final:
          type: boolean
          description: '`True` = this is the final snapshot which will be used for voting power in the event.</br>`False` =This is an interim snapshot, subject to change.'
      required:
        - voter_info
        - last_updated
      x-stoplight:
        id: gce0oy7wdls7g
    VoterInfo:
      type: object
      description: voter's info
      example:
        voting_power: 1000
        voting_group: rep
        delegations_power: 400
        delegations_count: 200
        voting_power_saturation: 0.5
      properties:
        voting_power:
          description: voter's voting power
          type: integer
          format: u64
        voting_group:
          $ref: '#/components/schemas/VoterGroupId'
        delegations_power:
          description: 'voter''s delegation''s power, which represents total voting power which was delegated to this voter'
          type: integer
          format: u64
        delegations_count:
          description: 'amount of delegators, who was delegated to this voter'
          type: integer
          format: u64
        voting_power_saturation:
          description: voting power's share of the total voting power corresponds to the current voting group
          type: number
          format: float
          minimum: 0
          maximum: 100
      required:
        - voting_power
        - voting_group
        - delegations_power
        - delegations_count
        - voting_power_saturation
      x-stoplight:
        id: xqfzipvfkm1o4
    DelegationInfo:
      type: object
      description: voters delegation info
      example:
        voting_key: f5285eeead8b5885a1420800de14b0d1960db1a990a6c2f7b517125bedc000db
        group: rep
        weight: 5
        value: 12345
      properties:
        voting_key:
          type: string
          pattern: '[0-9a-f]{64}'
          description: Hex encoded voting key
        group:
          $ref: '#/components/schemas/VoterGroupId'
        weight:
          type: number
          format: u64
          description: Relative weight assigned to this voting key.
        value:
          type: number
          format: u64
          description: Raw voting power distributed to this voting key.
      required:
        - voting_key
        - group
        - weight
        - value
      x-stoplight:
        id: 8muubqcedp93n
    DelegatorInfo:
      title: DelegatorInfo
      x-stoplight:
        id: gs0t1s4y1d5ay
      type: object
      properties:
        delegations:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: '#/components/schemas/DelegationInfo'
        raw_power:
          type: number
          description: Raw total voting power from stake address
        total_power:
          type: number
          description: 'Total voting power, across all registered voters.'
        last_updated:
          type: string
          format: date-time
          description: Date and time for the latest update to this snapshot information.
        as_at:
          type: string
          format: date-time
          description: Date and time the latest snapshot represents.
        final:
          type: boolean
          description: '`True` = this is the final snapshot which will be used for voting power in the event.</br>`False` =This is an interim snapshot, subject to change.'
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Catalyst Auth Token
  responses:
    '500':
      description: Internal Error
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
    404-Event:
      description: Voting Event Not Found
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
  parameters:
    event_id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
      description: The ID Number of the Voting Event. As reported by `/api/v1/events`.
    obj_id:
      name: obj_id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
      description: 'The ID number of the Objective in a Voting Event. As reported by `/api/v1/event/{id}/objectives`.'
    prop_id:
      name: prop_id
      in: path
      required: true
      schema:
        type: string
      description: The ID Number of the Proposal within a Objective of a Voting Event
    limit:
      name: lim
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 2147483647
        example: 100
      description: Limit the results to this value
      style: form
    offset:
      name: ofs
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 0
        minimum: 0
      description: Offset the results starting at this record. 0 being the first.
      style: form
    voter_groups_filter:
      name: grp
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          enum:
            - direct
            - rep
          example: direct
        uniqueItems: true
        minItems: 1
      description: Filter Results to only these voter groups.
      explode: true
      style: form
    totals:
      name: tot
      in: query
      required: false
      schema:
        type: boolean
        default: false
        example: true
      description: 'Don''t return results, just the total number of results that could have been returned.'
    voting_key:
      name: vkey
      in: path
      required: true
      schema:
        type: string
      description: A Voting Key.
    stake_public_key:
      name: sp_key
      in: path
      required: true
      schema:
        type: string
      description: Stake Public key
    event_id_filter:
      name: eid
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 11
        minimum: 0
      description: The Event ID to return results for.
      style: form
